from __future__ import annotations

import os
import pandas as pd


def load_csv(path: str) -> pd.DataFrame:
    if not os.path.exists(path):
        return pd.DataFrame()
    if os.path.getsize(path) == 0:
        return pd.DataFrame()
    return pd.read_csv(path)


def safe_float(x):
    try:
        return float(x)
    except Exception:
        return None


def main():
    root = os.getcwd()

    # User-provided inputs (already uploaded / generated)
    universe_summary_path = os.path.join(root, "universe_summary.csv")
    opp_scorecard_path = os.path.join(root, "opportunity_scorecard_universe.csv")

    # Generated by Module P1
    ema_pivot_profile_path = os.path.join(root, "data", "research", "conservative", "ema_pivot_profile_universe.csv")

    uni = load_csv(universe_summary_path)
    opp = load_csv(opp_scorecard_path)
    piv = load_csv(ema_pivot_profile_path)

    if uni.empty:
        raise SystemExit(f"Missing/empty: {universe_summary_path}")
    if opp.empty:
        print(f"⚠️ Missing/empty: {opp_scorecard_path} (we can still rank without it)")
    if piv.empty:
        print(f"⚠️ Missing/empty: {ema_pivot_profile_path} (we can still rank without it)")

    # Normalize symbol column names
    for df in [uni, opp, piv]:
        if not df.empty and "symbol" in df.columns:
            df["symbol"] = df["symbol"].astype(str).str.upper()

    # Merge
    merged = uni.copy()
    if not piv.empty:
        merged = merged.merge(piv, on="symbol", how="left", suffixes=("", "_piv"))
    if not opp.empty:
        merged = merged.merge(opp, on="symbol", how="left", suffixes=("", "_opp"))

    # ---- Build Ranking Signals ----
    # Compatibility score (EMA structure)
    # Higher is better. Penalize violations.
    # We keep it interpretable and robust to missing values.
    def compatibility_score(r) -> float:
        ema_respect = safe_float(r.get("avg_ema_respect_ratio"))
        ema_viol = safe_float(r.get("avg_ema_violation_count"))
        pivot_h = safe_float(r.get("avg_pivot_height_perc"))
        compression = safe_float(r.get("avg_compression_ratio"))

        score = 0.0
        w = 0.0

        if ema_respect is not None:
            score += 60.0 * ema_respect
            w += 60.0
        if ema_viol is not None:
            # Violations hurt; normalize by a loose scale
            score += 20.0 * max(0.0, 1.0 - (ema_viol / 20.0))
            w += 20.0
        if pivot_h is not None:
            # Pivot height helps; cap
            score += 10.0 * min(max(pivot_h, 0.0), 2.0) / 2.0
            w += 10.0
        if compression is not None:
            score += 10.0 * min(max(compression, 0.0), 1.0)
            w += 10.0

        return (score / w * 100.0) if w > 0 else 0.0

    merged["compatibility_score"] = merged.apply(compatibility_score, axis=1)

    # Opportunity score (does the market give 1R moves?)
    # We use whichever columns exist in your opp scorecard.
    # Common columns we’ve used: opportunity_days_1r, opportunity_rate_1r, avg_mfe_r, avg_mae_r etc.
    def opportunity_score(r) -> float:
        # Try to find best available columns
        opp_rate = safe_float(r.get("directional_opportunity_rate_1r")) or safe_float(r.get("opportunity_rate_1r"))
        opp_days = safe_float(r.get("opportunity_days_1r")) or safe_float(r.get("orb_defined_1r_opportunity_days"))
        avg_mfe = safe_float(r.get("avg_future_mfe_r")) or safe_float(r.get("traded_days_avg_future_mfe_r"))
        avg_mae = safe_float(r.get("avg_future_mae_r")) or safe_float(r.get("traded_days_avg_future_mae_r"))

        score = 0.0
        w = 0.0

        if opp_rate is not None:
            score += 50.0 * min(max(opp_rate, 0.0), 1.0)
            w += 50.0
        if opp_days is not None:
            # More opportunity days matters, but cap to avoid domination
            score += 20.0 * min(opp_days, 20.0) / 20.0
            w += 20.0
        if avg_mfe is not None:
            # Prefer higher MFE
            score += 20.0 * min(max(avg_mfe, 0.0), 3.0) / 3.0
            w += 20.0
        if avg_mae is not None:
            # Less negative MAE is better; convert to 0..1
            # if mae is -1.5R -> bad; -0.2R -> good
            mae_norm = 1.0 - min(max(abs(avg_mae), 0.0), 2.0) / 2.0
            score += 10.0 * mae_norm
            w += 10.0

        return (score / w * 100.0) if w > 0 else 0.0

    merged["opportunity_score"] = merged.apply(opportunity_score, axis=1)

    # Final score: bias toward compatibility (we want quality)
    merged["final_rank_score"] = 0.65 * merged["compatibility_score"] + 0.35 * merged["opportunity_score"]

    # Sort
    merged = merged.sort_values("final_rank_score", ascending=False).reset_index(drop=True)

    # Output files
    out_dir = os.path.join(root, "data", "research")
    os.makedirs(out_dir, exist_ok=True)

    ranked_path = os.path.join(out_dir, "universe_ranked.csv")
    merged.to_csv(ranked_path, index=False)

    topN = 20
    watchlist = merged.head(topN)[["symbol", "final_rank_score", "compatibility_score", "opportunity_score"]].copy()
    watchlist_path = os.path.join(out_dir, f"universe_watchlist_top{topN}.csv")
    watchlist.to_csv(watchlist_path, index=False)

    print("\n✅ Ranked universe saved ->", ranked_path)
    print("✅ Watchlist saved ->", watchlist_path)
    print("\nTop 20 watchlist:")
    print(watchlist.to_string(index=False))


if __name__ == "__main__":
    main()
