import sqlite3
import pandas as pd
from datetime import datetime
import logging
import os

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

class OptionsWorldStateLogger:
    """
    Logs the massive 3D state space of the options market at the exact
    millisecond a decision is generated by the engine.
    This database will become the foundational training set for the future AI.
    """
    def __init__(self, db_dir="."):
        self.db_path = os.path.join(db_dir, "omega_telemetry.db")
        self._initialize_db()

    def _initialize_db(self):
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        
        # 1. State Table: Logs the macro and underlying state
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS underlying_state (
                state_id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp TEXT NOT NULL,
                ticker TEXT NOT NULL,
                underlying_price REAL NOT NULL,
                vix_value REAL, 
                spy_trend REAL,
                macro_context TEXT,
                UNIQUE(timestamp, ticker)
            )
        ''')
        
        # Seamlessly migration for the Phase 17 Macro World State expansion 
        try:
            cursor.execute("ALTER TABLE underlying_state ADD COLUMN macro_context TEXT")
        except sqlite3.OperationalError:
            pass
            
        # Phase 26 Migration: Injecting Discrete Volatility Vectors for the Phase 18 Deep Learner
        try:
            cursor.execute("ALTER TABLE underlying_state ADD COLUMN iv_rank REAL")
            cursor.execute("ALTER TABLE underlying_state ADD COLUMN bbw REAL")
        except sqlite3.OperationalError:
            pass
        
        # 2. Options Surface Table: Logs the exact Greeks and IV of the options on the chain
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS options_surface (
                surface_id INTEGER PRIMARY KEY AUTOINCREMENT,
                state_id INTEGER NOT NULL,
                contract_symbol TEXT NOT NULL,
                option_type TEXT NOT NULL, -- 'call' or 'put'
                expiration_date TEXT NOT NULL,
                dte INTEGER NOT NULL,      -- Days To Expiration
                strike REAL NOT NULL,
                bid REAL NOT NULL,
                ask REAL NOT NULL,
                mid_price REAL NOT NULL,
                implied_volatility REAL,
                delta REAL,
                gamma REAL,
                theta REAL,
                vega REAL,
                FOREIGN KEY(state_id) REFERENCES underlying_state(state_id)
            )
        ''')
        
        # 3. Actions Table: Logs what the AI/Engine decided to do based on this state
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS engine_actions (
                action_id INTEGER PRIMARY KEY AUTOINCREMENT,
                state_id INTEGER NOT NULL,
                action_type INTEGER NOT NULL, -- e.g., 0: do nothing, 1: buy call 0dte, etc.
                selected_contract TEXT,       -- Optional: The specific contract chosen
                confidence_score REAL,
                target_dte INTEGER,           -- Phase 26: The structurally targeted DTE bounds
                FOREIGN KEY(state_id) REFERENCES underlying_state(state_id)
            )
        ''')
        
        # Phase 26 Migration: DTE Integer Tracking
        try:
            cursor.execute("ALTER TABLE engine_actions ADD COLUMN target_dte INTEGER")
        except sqlite3.OperationalError:
            pass

        # 4. Result/PnL Table: To be updated later when trade is closed (Reward signal)
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS trade_results (
                result_id INTEGER PRIMARY KEY AUTOINCREMENT,
                action_id INTEGER NOT NULL,
                entry_timestamp TEXT NOT NULL,
                exit_timestamp TEXT,
                entry_price REAL,
                exit_price REAL,
                realized_pnl REAL,
                exit_code INTEGER,
                FOREIGN KEY(action_id) REFERENCES engine_actions(action_id)
            )
        ''')
        
        # Phase 29: AI Exit Reward State Capture Migration
        try:
            cursor.execute("ALTER TABLE trade_results ADD COLUMN exit_code INTEGER")
        except sqlite3.OperationalError:
            pass
        
        conn.commit()
        conn.close()
        
        # Suppress duplicate logs natively since OmegaBaselineActor AND the main engine both invoke this layer
        cls = self.__class__
        if not getattr(cls, '_initialized_logged', False):
            logger.info(f"Initialized Omega Telemetry Database at {self.db_path}")
            setattr(cls, '_initialized_logged', True)

    def log_state_and_action(self, timestamp: str, ticker: str, underlying_price: float, 
                             vix: float, spy_trend: float, options_chain: pd.DataFrame, 
                             action_type: int, macro_context: dict = None, selected_contract: str = None,
                             iv_rank: float = None, bbw: float = None, target_dte: int = None):
        """
        Logs the full state consisting of the underlying, the entire relevant options chain,
        the global macro-economic JSON, and the final action taken.
        """
        import json
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        
        try:
            macro_str = json.dumps(macro_context) if macro_context else "{}"
            
            # 1. Insert underlying state
            cursor.execute('''
                INSERT INTO underlying_state (timestamp, ticker, underlying_price, vix_value, spy_trend, macro_context, iv_rank, bbw)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            ''', (timestamp, ticker, underlying_price, vix, spy_trend, macro_str, iv_rank, bbw))
            
            state_id = cursor.lastrowid
            
            # 2. Insert options surface (bulk insert)
            if not options_chain.empty:
                records = []
                for _, row in options_chain.iterrows():
                    mid_price = (row['bid'] + row['ask']) / 2.0
                    records.append((
                        state_id, row['contract_symbol'], row['option_type'], row['expiration_date'],
                        row['dte'], row['strike'], row['bid'], row['ask'], mid_price,
                        row.get('implied_volatility'), row.get('delta'), row.get('gamma'),
                        row.get('theta'), row.get('vega')
                    ))
                
                cursor.executemany('''
                    INSERT INTO options_surface (
                        state_id, contract_symbol, option_type, expiration_date, dte, strike, 
                        bid, ask, mid_price, implied_volatility, delta, gamma, theta, vega
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                ''', records)

            # 3. Insert Action Logger
            cursor.execute('''
                INSERT INTO engine_actions (state_id, action_type, selected_contract, target_dte)
                VALUES (?, ?, ?, ?)
            ''', (state_id, action_type, selected_contract, target_dte))
            
            conn.commit()
            logger.info(f"Successfully logged state and action {action_type} for {ticker} at {timestamp}")

        except Exception as e:
            conn.rollback()
            logger.error(f"Failed to log state: {e}")
        finally:
            conn.close()

if __name__ == "__main__":
    # Test initialization
    logger_instance = OptionsWorldStateLogger()
