import json
import logging
import time
import sys
import os
import requests

from trade_telemetry import log_trade, init_telemetry_db

# Setup Telemetry Logging for the Execution Bridge
logging.basicConfig(
    filename='execution_bridge.log',
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)

# --- DISCORD WEBHOOK ---
DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1477096087998431366/skOt4ngKGR31LU2aup7PXUfSeQmleDaAkKFdXMx3jSSIGx-6n2VWiVTX68ZQZ32SGmtP"

def load_accounts():
    """Loads the multi-account configuration file."""
    config_path = os.path.join(os.path.dirname(__file__), 'alpaca_accounts.json')
    try:
        with open(config_path, 'r') as f:
            return json.load(f)
    except Exception as e:
        logging.critical(f"Failed to load alpaca_accounts.json: {e}")
        raise

def connect_to_broker(base_url, headers):
    """Initializes the connection to the Alpaca Broker by checking the account status."""
    logging.info(f"Connecting to Alpaca Broker API at {base_url}...")
    try:
        response = requests.get(f"{base_url}/v2/account", headers=headers)
        if response.status_code == 200:
            account = response.json()
            logging.info(f"Connected successfully. Account Status: {account.get('status')}")
            return True
        else:
            raise Exception(f"HTTP {response.status_code}: {response.text}")
    except Exception as e:
        logging.critical(f"Broker Connection Failed: {e}")
        raise

def check_market_hours(base_url, headers):
    """Verifies that the US Equity Market is currently open. Prevents weekend/holiday executions."""
    logging.info("Checking Alpaca Market Clock...")
    try:
        response = requests.get(f"{base_url}/v2/clock", headers=headers)
        if response.status_code == 200:
            clock = response.json()
            is_open = clock.get("is_open", False)
            return is_open
        else:
             logging.error(f"Failed to fetch market clock: HTTP {response.status_code}")
             return True # Default to true to not block if clock API fails
    except Exception as e:
        logging.error(f"Clock ping failed: {e}")
        return True # Default to true if API fails

def get_account_equity(base_url, headers):
    """Fetches total portfolio value (cash + equities) to determine sizing."""
    try:
        response = requests.get(f"{base_url}/v2/account", headers=headers)
        if response.status_code == 200:
            account = response.json()
            equity = float(account.get('equity', 0))
            logging.info(f"Total Account Equity: ${equity:,.2f}")
            return equity
        else:
            raise Exception(f"HTTP {response.status_code}: {response.text}")
    except Exception as e:
        logging.critical(f"Failed to fetch account equity: {e}")
        raise

def parse_target_portfolio(json_path='live_target_portfolio.json'):
    """Reads the JSON payload generated by the Alpha Engine."""
    try:
        with open(json_path, 'r') as f:
            data = json.load(f)
        logging.info(f"Loaded Target Portfolio generated on {data['timestamp']}")
        return data
    except Exception as e:
        logging.critical(f"Failed to load JSON target portfolio: {e}")
        raise

def get_current_positions(base_url, headers):
    """Fetches currently held symbols and exact quantities from the live broker."""
    logging.info("Fetching current live equity positions from Broker...")
    try:
        response = requests.get(f"{base_url}/v2/positions", headers=headers)
        if response.status_code == 200:
            positions = response.json()
            # ALPHA ENGINE FIREWALL: 
            # We share the API key with the Omega Engine (which trades us_option).
            # We must exclusively filter for 'us_equity' so Alpha is physically blind 
            # to Omega's Options and does not automatically liquidate them!
            pos_dict = {
                pos["symbol"]: float(pos["qty"]) 
                for pos in positions 
                if pos.get("asset_class", "us_equity") == "us_equity"
            }
            logging.info(f"Current Live Alpha Positions (Equities Only): {list(pos_dict.keys())}")
            return pos_dict
        else:
             raise Exception(f"HTTP {response.status_code}: {response.text}")
    except Exception as e:
        logging.error(f"Failed to fetch live positions: {e}")
        raise

def get_latest_price(symbol, headers):
    """Fetches the latest real-time or previous close price from Alpaca Market Data."""
    try:
        # The Market Data endpoint handles both Paper and Live keys automatically
        url = f"https://data.alpaca.markets/v2/stocks/snapshots?symbols={symbol}"
        response = requests.get(url, headers=headers)
        if response.status_code == 200:
            data = response.json()
            snapshot = data.get(symbol, {})
            
            # Prefer the exact last tick, fallback to the daily close
            if snapshot.get('latestTrade'):
                return float(snapshot['latestTrade']['p'])
            elif snapshot.get('dailyBar'):
                return float(snapshot['dailyBar']['c'])
            elif snapshot.get('prevDailyBar'):
                return float(snapshot['prevDailyBar']['c'])
            else:
                raise Exception("No price components found in snapshot data.")
        else:
            raise Exception(f"HTTP {response.status_code}: {response.text}")
    except Exception as e:
        logging.error(f"Failed to fetch price for {symbol} via Alpaca: {e}")
        return None

def execute_market_on_close(symbol, side, base_url, headers, qty=1):
    """
    Fires a Market-On-Close (MOC) order to the exchange with a 3x retry failsafe.
    These orders guarantee execution at the 4:00 PM EST closing print.
    """
    max_retries = 3
    for attempt in range(max_retries):
        logging.info(f"Routing {side.upper()} order for {symbol} to Exchange (MARKET) - Attempt {attempt + 1}...")
        try:
            payload = {
                "symbol": symbol,
                "qty": qty, # Production: Use notional cash sizing or qty
                "side": side,
                "type": "market",
                "time_in_force": "day"
            }
            res = requests.post(f"{base_url}/v2/orders", json=payload, headers=headers)
            
            if res.status_code == 200:
                logging.info(f"[SUCCESS] Sent MARKET {side.upper()} order for {symbol}.")
                return True
            else:
                 raise Exception(f"HTTP {res.status_code}: {res.text}")
                 
        except Exception as e:
            logging.error(f"Order routing failed for {symbol}: {e}")
            if attempt < max_retries - 1:
                logging.info(f"Retrying in 5 seconds...")
                time.sleep(5)
            else:
                logging.critical(f"FATAL: Failed to route {side.upper()} order for {symbol} after {max_retries} attempts.")
                return False

def send_discord_notification(equity, target_symbols, executed_sells, executed_buys, is_bullish, account_name):
    """Sends a rich embedded message to Discord covering portfolio updates."""
    if not DISCORD_WEBHOOK_URL:
        return
        
    date_str = time.strftime("%Y-%m-%d")
    
    # Determine color and title representing the day's actions
    if not is_bullish:
        color = 16711680 # Red
        title = f"🔴 [{account_name}] MACRO HALT: Cash Protection Mode"
        desc = "The S&P 500 has fallen below its 200 SMA. The Alpha Engine has liquidated the portfolio to protect capital."
    elif executed_buys or executed_sells:
        color = 3447003 # Blue
        title = f"🔄 [{account_name}] Portfolio Rebalanced"
        desc = "The quantitative engine has executed rotation orders to capture new momentum leaders."
    else:
        color = 65280 # Green
        title = f"✅ [{account_name}] Perfectly Synced"
        desc = "No trading actions required today. The portfolio is correctly allocated."

    embed = {
        "title": title,
        "description": desc,
        "color": color,
        "fields": [
            {
                "name": "💰 Total Account Equity",
                "value": f"${equity:,.2f}",
                "inline": False
            },
            {
                "name": "🎯 Current Alpha Targets",
                "value": ", ".join(target_symbols) if target_symbols else "None (100% Cash)",
                "inline": False
            }
        ],
        "footer": {
            "text": f"Alpha Engine Daily Execution Run • {date_str}"
        }
    }

    if executed_sells:
        embed["fields"].append({
            "name": "📉 Liquidated (Sell MOC)",
            "value": "\n".join([f"**{sym}**: {qty} shares" for sym, qty in executed_sells.items()]),
            "inline": True
        })
        
    if executed_buys:
        embed["fields"].append({
            "name": "📈 Acquired (Buy MOC)",
            "value": "\n".join([f"**{sym}**: {qty} shares @ ~${price:.2f}" for sym, qty, price in executed_buys]),
            "inline": True
        })

    payload = {
        "username": "Institutional Alpha Engine",
        "avatar_url": "https://i.imgur.com/4M34hiw.png",
        "embeds": [embed]
    }

    try:
        response = requests.post(DISCORD_WEBHOOK_URL, json=payload)
        if response.status_code in [200, 204]:
            logging.info(f"Discord notification sent successfully for {account_name}.")
        else:
            logging.error(f"Failed to send Discord notification: HTTP {response.status_code} - {response.text}")
    except Exception as e:
        logging.error(f"Discord Webhook Failed: {e}")

def sync_portfolio(target_symbols, equity, base_url, headers, target_contexts=None, max_alloc_percent=0.10):
    """
    Calculates the delta between what we currently own and what the Engine wants us to own.
    Allocates exactly `max_alloc_percent` (e.g., 10%) of total account equity per new target.
    Returns tracking structures for Discord alerts.
    """
    current_positions = get_current_positions(base_url, headers)
    current_symbols = list(current_positions.keys())
    
    executed_sells = {}
    executed_buys = []
    
    # Step 1: Liquidate Sell Signals
    sells = [sym for sym in current_symbols if sym not in target_symbols]
    for sym in sells:
        qty_to_sell = current_positions.get(sym, 1.0)
        price_est = get_latest_price(sym, headers)
        logging.info(f"SIGNAL DECEASED: Attempting to liquidate position in {sym} (Qty: {qty_to_sell})")
        if execute_market_on_close(sym, 'sell', base_url, headers, qty=qty_to_sell):
            executed_sells[sym] = qty_to_sell
            log_trade('SELL', sym, qty_to_sell, price_est if price_est else 0.0, state_context={"reason": "dropped_from_targets"})
        
    # Step 2: Acquire Buy Signals
    buys = [sym for sym in target_symbols if sym not in current_symbols]
    
    # Capital sizing math: 10% cash allocation per target symbol
    cash_allocation = equity * max_alloc_percent
    logging.info(f"Targeting ${cash_allocation:,.2f} allocation per new leader.")
    
    for sym in buys:
        price = get_latest_price(sym, headers)
        if not price:
             logging.error(f"Skipping entry for {sym} due to missing price data.")
             continue
             
        qty_to_buy = round(cash_allocation / price, 5)
        if qty_to_buy < 0.0001:
             logging.warning(f"Allocation for {sym} (${cash_allocation:,.2f}) is lower than minimum fractional share. Skipping.")
             continue
             
        logging.info(f"NEW LEADER DETECTED: {sym} @ ${price:.2f}. Allocating {qty_to_buy} shares.")
        if execute_market_on_close(sym, 'buy', base_url, headers, qty=qty_to_buy):
            executed_buys.append((sym, qty_to_buy, price))
            context = target_contexts.get(sym, {}) if target_contexts else {}
            
            # Extract scores for dedicated DB columns
            roc = context.get('ret_3m', 0.0) # Using 3m return as proxy for roc_score if not explicitly passed
            if 'score' in context:
                 roc = context['score']
                 
            vix = context.get('vix_level', 0.0)
            
            log_trade('BUY', sym, qty_to_buy, price, roc_score=roc, vix_level=vix, state_context=context)
        
    if not sells and not buys:
         logging.info("Portfolio is perfectly synced. No required actions for today.")
         print("Portfolio is fully synced with Alpha Targets.")
         
    return executed_sells, executed_buys

def run_execution_bridge():
    """Main Orchestrator for the execution bridge running across multiple accounts."""
    logging.info("--- STARTING EXECUTION BRIDGE ---")
    try:
        # Load the universal payload targets
        payload = parse_target_portfolio()
        targets = payload['target_symbols']
        contexts = payload.get('state_contexts', {})
        macro_bullish = payload['macro_bullish']
        
        # Load account credentials
        accounts_config = load_accounts()
        first_account = True
        
        for acct in accounts_config['accounts']:
            acct_name = acct['name']
            base_url = acct['base_url']
            max_alloc = acct.get('max_alloc_percent', 0.10)
            
            headers = {
                "APCA-API-KEY-ID": acct['key'],
                "APCA-API-SECRET-KEY": acct['secret'],
                "accept": "application/json"
            }
            
            logging.info(f"=== PROCESSING ACCOUNT: {acct_name} ===")
            print(f"=== PROCESSING ACCOUNT: {acct_name} ===")
            
            # Use the first account to check market hours once
            if first_account:
                if not check_market_hours(base_url, headers):
                    logging.warning("Market is currently CLOSED (Weekend, Holiday, or After-Hours). Halting Execution for all accounts.")
                    print("Market is currently CLOSED. Execution Bridge halted to prevent stale queued orders.")
                    return
                first_account = False
                
            # Connect and Fetch Equity
            connect_to_broker(base_url, headers)
            equity = get_account_equity(base_url, headers)
            
            # Macro Halt Check
            if not macro_bullish:
                logging.warning(f"[{acct_name}] CRITICAL: MACRO WEATHER IS BEARISH. FORCING 100% LIQUIDATION.")
                executed_sells, executed_buys = sync_portfolio([], equity, base_url, headers, {}, max_alloc)
                logging.info(f"[{acct_name}] Liquidation commands sent. Entering Cash Protection Mode.")
                send_discord_notification(equity, [], executed_sells, executed_buys, False, acct_name)
                continue

            # Sync Alpha Targets
            logging.info(f"[{acct_name}] Engine requested {len(targets)} symbols: {targets}")
            print(f"[{acct_name}] Targeting active allocations: {targets}")
            executed_sells, executed_buys = sync_portfolio(targets, equity, base_url, headers, contexts, max_alloc)
            
            # Send Rich Discord Notification for this specific account
            send_discord_notification(equity, targets, executed_sells, executed_buys, True, acct_name)
            
        logging.info("--- ALL ACCOUNTS PROCESSED. EXECUTION BRIDGE SLEEPING. ---")
        
    except Exception as e:
        logging.critical(f"FATAL: Execution Bridge Crashed. Intervention required. Error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    run_execution_bridge()
